<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>DotNet PG.snk</AssemblyOriginatorKeyFile>
        <PublicSign>true</PublicSign>
        <Title>DotNet PG</Title>
        <Authors>Nguyen Van Nguyen - nguyennv1981@gmail.com</Authors>
        <Description>DotNet PG is an implementation of the OpenPGP standard in .NET. It implements RFC 9580 and provides encryption with public key or symmetric cryptographic algorithms, digital signatures, compression, and key management.</Description>
        <Copyright>Copyright (c) Dot Net Privacy Guard Project. All rights reserved.</Copyright>
        <PackageProjectUrl>https://github.com/web-of-trust/dotnet-pg</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/web-of-trust/dotnet-pg/blob/main/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/web-of-trust/dotnet-pg</RepositoryUrl>
        <PackageTags>cryptography encryption signing openpgp rfc4880 privacy-guard rfc6637 rfc9580</PackageTags>
        <PackageReleaseNotes>First major release</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    </ItemGroup>

</Project>
